spring:
  application:
    name: front
  http:
    encoding:
      enabled: true
      force: true
      charset: UTF-8
  mustache:
    charset: UTF-8
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
    multipart:
      enabled: true

java-client:
  api:
    host: http://localhost:8081

feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true


